### ISSUE TITLE
Add support for Winter blocks

### ISSUE THREAD

**Issue by damsfx** [wintercms/vscode-extension#10]
It would be great to have support for `.block` files from the plugin [winter-blocks-plugin](https://github.com/wintercms/wn-blocks-plugin).  

The file schema : 
1. A Yaml section
2. An optional PHP section
3. a HTML/Twig section

I started the work here, but I don't have time to do more at the moment: 
https://github.com/damsfx/vscode-extension/tree/add-blocks

**Comment by bennothommo** [comment]
Block template highlighting is now available as of v0.4.0!
