### ISSUE TITLE
Error on type property

### ISSUE THREAD

**Issue by AIC-BV** [wintercms/vscode-extension#13]
![image](https://github.com/wintercms/vscode-extension/assets/89913092/e2474e14-68a5-476a-afc8-01b9a6fa27f4)

`type: x` in fields.yaml is throwing an error
"Matches multiple schemas when only one must validate."

Note:
It is not throwing the error inside nestedform, but I think that is because its not working in nestedform?

**Comment by bennothommo** [comment]
Fixed in v0.4.1.
