### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by WebVPF** [wintercms/vscode-extension#2]
Highlighting does not work in theme partials without '=='
Example `\themes\demo\partials\site\head.htm`

![no_hl](https://user-images.githubusercontent.com/61043464/153778534-f0ad9800-25ca-4d97-93d5-02f965783840.jpg)

![ok-hl](https://user-images.githubusercontent.com/61043464/153778542-e4f40fd7-5fab-491d-8164-c9c2a88f8454.jpg)

---

Code commenting not working with keyboard shortcuts <kbd>Ctrl</kbd> + <kbd>/</kbd>. For lang Winter CMS Template.
Works only for the INI section.

**Comment by bennothommo** [comment]
@WebVPF highlighting problem is a duplicate of #1 - there's a [comment there](https://github.com/wintercms/vscode-extension/issues/1#issuecomment-1038182974) explaining why you need the `==` currently.

As for the commenting issue, will take a look .
