### ISSUE TITLE
Form 'type' field value validation doesn't include any widget types

### ISSUE THREAD

**Issue by Flynsarmy** [wintercms/vscode-extension#6]
When creating a form field with type `richeditor` for example I get an error:
> Value must be "text" | "number" | ...

![Screen Shot 2022-03-19 at 10 53 44 pm](https://user-images.githubusercontent.com/334808/159121902-c1450e3d-fa34-4aeb-9324-0295a8651d05.png)

This seems to apply for any widget type - richeditor, relation, datepicker, datatable etc

**Comment by bennothommo** [comment]
@Flynsarmy it's been fixed here already - https://github.com/wintercms/vscode-extension/commit/d27d3a1026486e2cfe8ee22920a8c38b851a7c87, just need to stop slacking off and release a new version of the extension.

**Comment by bennothommo** [comment]
I've pushed out [v0.2.0](https://github.com/wintercms/vscode-extension/releases/tag/v0.2.0) which contains this fix as well as some other cool stuff. It should now be available on the Visual Code Marketplace.
