### ISSUE TITLE
Alternative Input preset converter throws an error

### ISSUE THREAD

**Issue by AIC-BV** [wintercms/vscode-extension#7]
![image](https://user-images.githubusercontent.com/89913092/168310383-27849843-73ca-429f-9ae4-a270a81a34f5.png)

See here: https://wintercms.com/docs/backend/forms#field-input-preset
![image](https://user-images.githubusercontent.com/89913092/168310604-c70ed48e-e63c-4096-9ffd-194dc3adf5c7.png)

**Comment by bennothommo** [comment]
This has been fixed as of 8a8b54e1bad0ecd75ce6a92edf20a98022eaf952, but it's waiting for the next release.
